/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as RepartidorRouteImport } from './routes/repartidor'
import { Route as RepartidoresRouteImport } from './routes/repartidores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidorRoute = RepartidorRouteImport.update({
  id: '/repartidor',
  path: '/repartidor',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidoresRoute = RepartidoresRouteImport.update({
  id: '/repartidores',
  path: '/repartidores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pedidos': typeof PedidosRoute
  '/repartidor': typeof RepartidorRoute
  '/repartidores': typeof RepartidoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pedidos': typeof PedidosRoute
  '/repartidor': typeof RepartidorRoute
  '/repartidores': typeof RepartidoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pedidos': typeof PedidosRoute
  '/repartidor': typeof RepartidorRoute
  '/repartidores': typeof RepartidoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/configuracion'
    | '/historial'
    | '/login'
    | '/menu'
    | '/pedidos'
    | '/repartidor'
    | '/repartidores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/configuracion'
    | '/historial'
    | '/login'
    | '/menu'
    | '/pedidos'
    | '/repartidor'
    | '/repartidores'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/configuracion'
    | '/historial'
    | '/login'
    | '/menu'
    | '/pedidos'
    | '/repartidor'
    | '/repartidores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  HistorialRoute: typeof HistorialRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  PedidosRoute: typeof PedidosRoute
  RepartidorRoute: typeof RepartidorRoute
  RepartidoresRoute: typeof RepartidoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidor': {
      id: '/repartidor'
      path: '/repartidor'
      fullPath: '/repartidor'
      preLoaderRoute: typeof RepartidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidores': {
      id: '/repartidores'
      path: '/repartidores'
      fullPath: '/repartidores'
      preLoaderRoute: typeof RepartidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  HistorialRoute: HistorialRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  PedidosRoute: PedidosRoute,
  RepartidorRoute: RepartidorRoute,
  RepartidoresRoute: RepartidoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
